CREATE TABLE `recaptcha_fails` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`IP` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`ID`),
	INDEX `IP` (`IP`)
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
