CREATE TABLE `roles` (
	`NAME_OF_ROLE` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`VALUE` TINYINT(3) UNSIGNED NOT NULL,
	`LANDING_PAGE` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`VALUE`)
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;
