CREATE TABLE `users_2fa` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`USER_ID` INT(10) UNSIGNED NULL DEFAULT NULL,
	`SECRET` VARCHAR(225) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `USER_ID` (`USER_ID`)
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
