CREATE TABLE `users_tokens` (
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`USER_ID` INT(11) UNSIGNED NOT NULL,
	`TOKEN` VARCHAR(63) NOT NULL COLLATE 'utf8mb4_bin',
	`CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	INDEX `USER_ID` (`USER_ID`),
	INDEX `TOKEN` (`TOKEN`),
	CONSTRAINT `USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `users` (`ID`)
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
