CREATE TABLE `debug_visits` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`IP` VARCHAR(16) NOT NULL DEFAULT '0' COLLATE 'utf8mb4_bin',
	`USER_USERNAME` VARCHAR(128) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`URL_STRING` TEXT NOT NULL COLLATE 'utf8mb4_bin',
	`CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`)
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
AUTO_INCREMENT=1
;
